# Generated by Django 3.1 on 2021-12-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userclass',
            options={'verbose_name_plural': 'User Classes'},
        ),
    ]
