# Generated by Django 3.1 on 2022-03-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
