# Generated by Django 3.1 on 2022-03-18 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_date', '-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['-created_date', '-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['-created_date', '-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_date', '-modified_date']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534885)),
        ),
        migrations.AddField(
            model_name='assignment',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534919)),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534885)),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534919)),
        ),
        migrations.AddField(
            model_name='instructor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534885)),
        ),
        migrations.AddField(
            model_name='instructor',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534919)),
        ),
        migrations.AddField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534885)),
        ),
        migrations.AddField(
            model_name='student',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534919)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534885)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534919)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534885)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534919)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534885)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 38, 37, 534919)),
        ),
    ]
