# Generated by Django 3.1 on 2022-03-18 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220318_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 39, 32, 222095, tzinfo=utc)),
        ),
    ]
