# Generated by Django 3.1 on 2022-06-23 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220609_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='file_link',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='api.classroom'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
