# Generated by Django 3.1 on 2022-07-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220704_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='code',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
