# Generated by Django 3.1 on 2022-02-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignment_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='duration',
            field=models.DateTimeField(blank=True),
        ),
    ]
