# Generated by Django 3.1 on 2022-07-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220705_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
