# Generated by Django 3.1 on 2022-02-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220223_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='duration',
        ),
    ]
