# Generated by Django 3.1 on 2022-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220726_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'draft'), ('SUBMITTED', 'submitted')], default='SUBMITTED', max_length=15),
        ),
    ]
