# Generated by Django 3.1 on 2022-12-03 15:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221121_0500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={},
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='document',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='name',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.file_generate_upload_path),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='original_file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
