# Generated by Django 3.1 on 2022-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20221203_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
