# Generated by Django 3.1 on 2022-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20221208_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
    ]
