# Generated by Django 3.1 on 2022-12-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_student_is_representative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_representative',
            new_name='is_class_representative',
        ),
    ]
