# Generated by Django 3.1 on 2022-12-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20221208_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_class_representative',
            new_name='class_representative',
        ),
    ]
