# Generated by Django 3.1 on 2022-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='upload_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
