# Generated by Django 3.1 on 2022-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_submission_upload_finished_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_for_student'),
        ),
    ]
